blogsite/blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed

# TIP Creating a urls.py file for each application is the best way to make your applications reusable by other projects.
app_name = 'blog'  # application namespace

urlpatterns = [
    # post views
    path('', views.post_list, name='post_list'), #regular function list
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),  # regular function list
    #path('', views.PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',
         views.post_detail,
         name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search'),

]

blogsite/blogsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap')
]

blogsite/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager

# Creating custom model manager
class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager,
                     self).get_queryset().filter(status='published')


# Create your models here.

class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', "Published")
    )

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250,
                            unique_for_date='publish')
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,
                              choices=STATUS_CHOICES,
                              default='draft')

    # default manager
    object = models.Manager()
    # custom published manager
    published = PublishedManager()
    # tagging manager
    tags = TaggableManager() # The tags manager will allow you to add, retrieve, and remove tags from Post objects.

    class Meta:
        ordering = ('-publish',)  # default ordering of the posts when querring the database (- descending)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       args=[self.publish.year,
                             self.publish.month,
                             self.publish.day, self.slug])


class Comment(models.Model):
    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE,
                             related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f"Comment by {self.name} on {self.post}"

blogsite/blog/forms.py
from django import forms
from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False,
                               widget=forms.Textarea)


class CommentForm(forms.ModelForm):  # Dynamicly create form from model
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')  # which fields fo model are user for form


class SearchForm(forms.Form):
    query = forms.CharField()

blogsite/blog/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank
from .models import Post, Comment
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from .forms import EmailPostForm, CommentForm, SearchForm
from django.core.mail import send_mail
from blogsite.settings import EMAIL_HOST_USER
from taggit.models import Tag
from django.db.models import Count # This is the Count aggregation function of the Django ORM. This function will allow you to perform aggregated counts of tags. django.db.models includes the following aggregation functions:


def post_search(request):
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET: # send the form using the GET method instead of POST
        form = SearchForm(request.GET) #When the form is submitted, you instantiate it with the submitted GET data, and verify that the form data is valid
        if form.is_valid():
            query = form.cleaned_data['query']
            #create a SearchQuery object, filter results by it, and use SearchRank to order the results by relevancy.
            search_vector = SearchVector('title', 'body')
            search_query = SearchQuery(query)

            results = Post.published.annotate(
                search=search_vector,
                rank=SearchRank(search_vector, search_query)
            ).filter(search=search_query).order_by('-rank')

    return render(request,
                  'blog/post/search.html',
                  {'form': form,
                   'query':query,
                   'results':results}
                  )

# Class based view see urls.py in blog app to usage
class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = "posts"
    paginate_by = 3
    template_name = 'blog/post/list.html'


# Regular mangual view
def post_list(request, tag_slug=None):  # parametr reqeust jest wymagany przez wszystkie funkcjie widoków
    posts = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        posts = posts.filter(tags__in=[tag])
    paginator = Paginator(posts, 3)  # 3 post in each page
    print(request.GET)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # if page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # if page is out of range deliver last page of result
        posts = paginator.page(paginator.num_pages)

    return render(request=request, template_name='blog/post/list.html',
                  context={'posts': posts, 'page': page, 'tag': tag})


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,
                                   status='published',
                                   publish__year=year,
                                   publish__month=month,
                                   publish__day=day)
    # List of active comments for this post
    comments = post.comments.filter(active=True)
    new_comment = None
    if request.method == 'POST':
        # A comment was posted
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
    else:
        comment_form = CommentForm()

    # List of similar posts using model agregatuin functions
    post_tags_ids = post.tags.values_list('id', flat=True) # retrieve list of ids of the tags of current post values_list() QuerySet returns tuples with the values for the given fields. You pass flat=True to it to get single values such as [1, 2, 3, ...] instead of one-tuples such as [(1,), (2,), (3,) ...].
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id) # Get all posts that contain any of these tags excluding current post
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4] # You use the Count aggregation function to generate a calculated field—same_tags—that contains the number of tags shared with all the tags queried.
    # then You order the result by the number of shared tags (descending order) and by publish to display recent posts first for the posts with the same number of shared tags. You slice the result to retrieve only the first four posts.


    return render(request,
                  'blog/post/detail.html',
                  {'post': post,
                   'comments': comments,
                   'new_comment': new_comment,
                   'comment_form': comment_form,
                   'similar_posts': similar_posts})


def post_share(request, post_id):
    # Retrive post by id
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False
    if request.method == 'POST':
        # Form was submited
        form = EmailPostForm(request.POST)  # from filled with user data
        if form.is_valid():
            # Form fields passes validation
            cd = form.cleaned_data  # If your form data does not validate, cleaned_data will contain only the valid
            # fields.
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} recomends your read {post.title}"
            message = f"Read {post.title} at {post_url} \n\n {cd['name']} 's comments: {cd['comments']}"
            send_mail(subject, message, EMAIL_HOST_USER, [cd['to']])
            sent = True
    else:
        form = EmailPostForm()  # empty form
    return render(request, 'blog/post/share.html', {'post': post, 'form': form, 'sent': sent})

blogsite/blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% block title %} {{ post.title }} {% endblock %}
{% block content %}

    <h1>{{ post.title }}</h1>
    <p class="tags">
        Tags:
          {% for tag in post.tags.all %}
            <a href="{% url "blog:post_list_by_tag" tag.slug %}">
              {{ tag.name }}
            </a>
            {% if not forloop.last %}, {% endif %}
          {% endfor %}
    </p>
    <p class="date">
        Published {{ post.publish }} by {{ post.author }}
    </p>
    {{ post.body|markdown }}
    <p>
        <a href="{% url "blog:post_share" post.id %}">Share this post</a>
    </p>
    {% with comments.count as total_comments %} {# Assign wariable to total_coments if valid in whole with block  The {% with %} template tag is useful for avoiding hitting the database or accessing expensive methods multiple times.#}
        <h2> {# comments.count is a querry set calling ORM method #}
            {{ total_comments }} comment{{ total_comments|pluralize }}
        </h2>
    {% endwith %}

    <h2>Similar posts</h2>
    {% for post in similar_posts %}
      <p>
        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
      </p>
    {% empty %}
      There are no similar posts yet.
    {% endfor %}

    {% for comment in comments %}
        <div class="comment">
            <p class="info">
                Comment {{ forloop.counter }} by {{ comment.name }}
                {{ comment.created }}
            </p>
        {{ comment.body|linebreaks }}
        </div>
    {% empty %}
        <p>There are no comments yet</p>
    {% endfor %}
    {% if new_comment %}
      <h2>Your comment has been added.</h2>
    {% else %}
      <h2>Add a new comment</h2>
      <form method="post">
        {{ comment_form.as_p }}
        {% csrf_token %}
        <p><input type="submit" value="Add comment"></p>
      </form>
    {% endif %}

{% endblock %}

blogsite/blog/templates/blog/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
    <li>
        <a href="{{ post.get_absolute_url }}"> {{ post.title }}</a>
    </li>
    {% endfor %}
</ul>

blogsite/blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% block title %}To jest blog{% endblock %}
{% block content %}
    <h1>Moj srok</h1>
    {% if tag %}
        <h2>Posts tagged with "{{ tag.name }}"</h2>
    {% endif %}

    {% for post in posts %}
        <h2>
            <a href="{{ post.get_absolute_url }}">
                {{ post.title }}
                <p class="tags">
                    Tags:
                      {% for tag in post.tags.all %}
                        <a href="{% url "blog:post_list_by_tag" tag.slug %}">
                          {{ tag.name }}
                        </a>
                        {% if not forloop.last %}, {% endif %}
                      {% endfor %}
                </p>
            </a>
        </h2>
        <p class="date">
            Published {{ post.publish }} by {{ post.author }}
        </p>
        {{ post.body|markdown|truncatewords_html:30 }}

    {% endfor %}

    {# Adding Paginaton form view #}
    {# Django's ListView generic view passes the selected page in a variable called page_obj #}
    {% include "pagination.html" with page=posts %}
{% endblock %}

blogsite/blog/templates/blog/post/search.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% block title %}Search{% endblock %}
{% block content %}
  {% if query %}
    <h1>Posts containing "{{ query }}"</h1>
    <h3>
      {% with results.count as total_results %}
        Found {{ total_results }} result{{ total_results|pluralize }}
      {% endwith %}
    </h3>
    {% for post in results %}
      <h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
      {{ post.body|markdown|truncatewords_html:5 }}
    {% empty %}
      <p>There are no results for your query.</p>
    {% endfor %}
    <p><a href="{% url "blog:post_search" %}">Search again</a></p>
  {% else %}
    <h1>Search for posts</h1>
    <form method="get">
      {{ form.as_p }}
      <input type="submit" value="Search">
    </form>
  {% endif %}
{% endblock %}

blogsite/blog/templates/blog/post/share.html
{% extends "blog/base.html" %}
{% block title %}Share a post{% endblock %}
{% block content %}
  {% if sent %}
    <h1>E-mail successfully sent</h1>
    <p>
      "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.
    </p>
  {% else %}
    <h1>Share "{{ post.title }}" by e-mail</h1>
    <form method="post">
        {% for field in form %}
          <div>
            {{ field.errors }}
            {{ field.label_tag }} {{ field }}
          </div>
        {% endfor %}
      {% csrf_token %}
      <input type="submit" value="Send e-mail">
    </form>
  {% endif %}
{% endblock %}